### ISSUE TITLE
Add image style tokens

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/token#13]
The functionality of [Imagecache Token](https://www.drupal.org/project/imagecache_token) could be merged directly into this module. ([It looks like this functionality is merged into token in D8](https://www.drupal.org/node/2611866).)

**Comment by herbdool** [comment]
Token is now in Backdrop core, so either try to get it into core or make it a new contrib.

**Comment by laryn** [comment]
Added this to the core queue. Thanks.
https://github.com/backdrop/backdrop-issues/issues/3594
