### ISSUE TITLE
Request to add a maintainer (quicksketch)

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/token#3]
Hi @enzolutions! Would it be okay if I helped in the porting of this module? Considering this module is targeted for inclusion in the next minor release, I'd like to start helping get it ready for core by porting some pieces that haven't been fully converted (like utilizing the new dialog API). Thanks!

**Comment by quicksketch** [comment]
Crosslinking with the same request for Pathauto: https://github.com/backdrop-contrib/pathauto/issues/13

**Comment by enzolutions** [comment]
Sure Nate

You have the roadmap clear, if you can create tasks for specific tasks I could try to help you

**Comment by quicksketch** [comment]
Thanks @enzolutions! With token I'm not sure what exact tasks are necessary. I'll have to dive into it and then make tickets as I go. I know for sure we should get the dialog converted to use the Backdrop Dialog API instead of a custom integration in Token. Beyond that, I'll have to take a look to know for sure. Thanks again!
